version: '3.7'
services:
    money-flask:
        #container_name: "money-flask"
        build: ./money-flask
        ports:
            - "${MONEY_FLASK_WEB_APP_PORT}:5000"
        volumes:
            - type: bind
              source: ../../project
              target: /project
        networks:
            - money
        command: python3 /project/app.py
    money-mongodb:
        #container_name: "money-mongodb"
        image: "mongo:3.6.0"
        volumes:
            - type: volume
              source: money-mongodb-data
              target: /data/db
            - type: volume
              source: money-mongodb-config
              target: /data/configdb
        networks:
            - money
volumes:
    money-mongodb-data:
    money-mongodb-config:
    money-mysql-data:
    money-mysql-test-data:
networks:
    money:

